# Generated by Django 5.0 on 2023-12-28 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kasturi', '0002_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='Kasturi.state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='country_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='Kasturi.country'),
        ),
    ]
