# Generated by Django 5.0 on 2023-12-28 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kasturi', '0003_alter_city_city_name_alter_city_state_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=120)),
                ('owner', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=10)),
                ('mail_id', models.EmailField(max_length=254)),
                ('district', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('pin_code', models.IntegerField()),
                ('service_type', models.CharField(max_length=20)),
                ('account_holder_name', models.CharField(max_length=50, verbose_name='A/C Holder Name')),
                ('account_number', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=11, verbose_name='IFSC Code')),
                ('branch_name', models.CharField(max_length=50)),
                ('pan_number', models.CharField(max_length=10)),
                ('gst_number', models.CharField(max_length=15, verbose_name='GSTIN Number')),
                ('payment_terms', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('address_proof', models.FileField(upload_to='documents/')),
                ('company_proof', models.FileField(upload_to='documents/')),
                ('cancelled_check', models.FileField(upload_to='documents/')),
                ('gst_in', models.FileField(upload_to='documents/')),
                ('pan_card', models.FileField(upload_to='documents/')),
                ('attachment1', models.FileField(upload_to='documents/')),
                ('agreement', models.FileField(upload_to='documents/')),
                ('tds_excemption_certificate', models.FileField(upload_to='documents/', verbose_name='TDS Excemption Certificate')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_city', to='Kasturi.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_country', to='Kasturi.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_states', to='Kasturi.state')),
            ],
        ),
    ]
